### ISSUE TITLE
B0 correction 

### ISSUE THREAD

**Issue by JeffFessler** [guanhuaw/MIRTorch#10]
It would be better to correct for B0 back to the RF pulse, where spins are in phase.
It would require that the user be able to pass in the time vector instead of using this range:
https://github.com/guanhuaw/MIRTorch/blob/da62806e49de4b2e7d88be1f727e7dba94d8556e/mirtorch/linear/mri.py#L413

**Comment by guanhuaw** [comment]
Thanks! It has been fixed.
