### ISSUE TITLE
Trajectory optimization example file?

### ISSUE THREAD

**Issue by hkaggarwal** [guanhuaw/MIRTorch#3]
Hello @guanhuaw, 

Thank you, for developing the MIRTorch package. 
I saw your recent work on BJORK. It is very nice read.

Can you please help me with any example code where you show how to take automatic derivative with respect to trajectory using the TorchKBNUFFT or MIRTorch (Or your efficient jacobian implements).  Somehow I could not find the file "example/demo_mri_traj.ipynb." Any suggestion will be helpful. 

Thanks,
Hemant
ps: In case, you would like to share the example file over the email: jnu.hemant@gmail.com

**Comment by guanhuaw** [comment]
hi @hkaggarwal , thanks for the question!
the code for the bjork project is in this repo: https://github.com/guanhuaw/Bjork

**Comment by hkaggarwal** [comment]
Thank you, @guanhuaw, for the reply.
