### ISSUE TITLE
Using the package for 3D NUFFT

### ISSUE THREAD

**Issue by Michaelsqj** [guanhuaw/MIRTorch#4]
Hi Guanhua,

Thank you so much for implementing such useful package. May I ask can this package be used for 3D differentiable NUFFT? I have some 3D non-Cartesian trajectories for which I wish to optimize the rotation angles by evaluating the uniformity of the sampling pattern.

Yours,
Qijia

**Comment by guanhuaw** [comment]
Hi @Michaelsqj ,
thanks for raising this up. Yeah, we do support 3d nufft. Please refer to the function docstring for the I/O formats (I will add this to the docs very soon.)
And please see this repo for the trajectory optimization: https://github.com/guanhuaw/Bjork

**Comment by guanhuaw** [comment]
Please also refer to our recent preprint on 3d optimization: https://arxiv.org/abs/2209.11030
